#!/bin/bash

file="checkmd5sum"
if [ ! -f "$file" ]; then
	touch "$file"
fi
now=$(md5sum /etc/crontab | awk {'print $1'})
subject="crontab modified"
read -r prev<$file

if [ "$prev" != "$now" ]; then
	echo "$subject" | mail -s "Crontab new settings" root@localhost 
fi
echo "$now">"$file"


#!/bin/bash
file="checkmd5sum"
if [ ! -f "$file" ]; then
	touch "$file"
fi
now=$(md5sum /etc/crontab | awk {'print $1'})
subject="crontab modified!"
read -r prev<$file

if [ "$prev" != "$now" ]; then
	echo "$subject" | mail -s "Crontab new settings" root@localhost 
fi
echo "$now">"$file"